### PR TITLE
Use MP Cookie to have tests persist

### PR DESCRIPTION
**Pull request by Erfaricy**
Hey,

Just made some changes on the Test persisting in the Mixpanel Cookie Object.

This way a variant will persist across refreshes and until a user clears a cookie. 

One caveat:
  The mixpanel.init function will need to change. Instead of using a `<script>` tag at the bottom, you will need to update the end of the MP Library to

```javascript
mixpanel.init('YOUR_MP_TOKEN', {'loaded': function(){  new Scenario({
  name: 'My Test Name',
})
.test({
  name: 'Test A',
  weight: 3, // The optional weight of the test. Each test has a weight of 1 by default
  className: 'foobar' // An optional class to add to the body tag. If left empty, the test name will be turned into a slug (i.e. "test-a")
})
.test({
  name: 'Test B'
  callback: function(){ console.log('I was chosen!'); } // An optional callback if the test is chosen
})
.go())
``` 

Let me know what you think.

Thanks,

Emmett

### CODE REVIEW

**Comment by jakiestfu** [comment]
Nice! If you can update the README.md, I will merge.

**Comment by Erfaricy** [comment]
Sure let me get that back to you in a little bit. 
Glad to help out.

**Comment by jakiestfu** [comment]
Also, is this logic optional?

**Comment by shonshampain** [comment]
Pls remove me from this list.

**Comment by Erfaricy** [comment]
In what sense? If they have not been served an experiment or a new experiment is starting it will follow your conventions.

It just stores the variant in the cookie, and we end up pulling the callback from the .tests when the MP lib is initialized.

**Comment by jakiestfu** [comment]
@shonshampain You can unsubscribe yourself, thanks.

**Comment by jakiestfu** [comment]
@Erfaricy What if the user doesn't do `mixpanel.init` and they start running tests? I'd hope the logic would be the same as it is now minus the persistence.

**Comment by Erfaricy** [comment]
I got to your code from a MP related article, it currently needs MP to run. I'm interested to help make it more functional for all.

**Comment by jakiestfu** [comment]
@Erfaricy What article?

**Comment by Erfaricy** [comment]
http://makerstudios.github.io/Scenario.js/#/intro-1 it was a presentation not an article apologies

**Comment by Erfaricy** [comment]
It seemed mp specific, I can work on one that is more optional.

**Comment by Erfaricy** [comment]
Let me work on one that is more optional, and then I'll make a different pull request.

**Comment by jakiestfu** [comment]
This pull is fine, I just want this persistence logic you've built to simply be optional. Not everyone would want persistence across their tests.

**Comment by Erfaricy** [comment]
Sounds good. 

Our main use in testing this on a simple page had a single user getting served different variants across refreshes which may be a jarring UX.

Just a sample use case;

I go to a landing page, you serve me variant A, I come back tomorrow and get served variant B and then make a purchase.

In a landing page -> Test Started -> Purchase conversion would incorrectly show Variant A.

Also by persisting it in MP cookie, we can then segment all user actions after they had been served a test experiment.

Is there a different use case where persistence would not be preferred? I understand to test if MP is not available, but for straight A/B testing wouldn't persistence for at least the length of the experiment be valuable?

**Comment by jakiestfu** [comment]
You're correct, @Erfaricy. Thanks for explaining your usage further.

**Comment by Erfaricy** [comment]
Just to be clear, would you prefer only the persistence to be optional or the requirement for MP to be optional?

**Comment by jakiestfu** [comment]
* Mixpanel: Required
* Persistence: Optional

That was my initial inquisition, but you've since swayed me to say that Persistence shouldn't be optional, I can't really find a use case where a non-persistent option would be beneficial.

**Comment by Erfaricy** [comment]
No worries here, I guess you could come up with a use case but it wouldn't be an A/B test just randomizing content. I will update the Readme.md and make another pull request then.

Glad we [MP] could help you out.

**Pull request closed without merging**
